using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma;
namespace Booma
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class BaseSubCommand6D : IWireMessage<BaseSubCommand6D>
    {
        public virtual Type SerializableType => typeof(BaseSubCommand6D);
        public virtual BaseSubCommand6D Read(Span<byte> buffer, ref int offset)
        {
            BaseSubCommand6D_Serializer.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public virtual void Write(BaseSubCommand6D value, Span<byte> buffer, ref int offset)
        {
            BaseSubCommand6D_Serializer.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="BaseSubCommand6D"/>
    /// </summary>
    public sealed partial class BaseSubCommand6D_Serializer
            : BasePolymorphicAutoGeneratedSerializerStrategy<BaseSubCommand6D_Serializer, BaseSubCommand6D, Byte>
    {
        protected override BaseSubCommand6D CreateType(int key)
        {
            switch (key)
            {
                case (int)Booma.SubCommand6DOperationCode.PlayerJoinedData:
                    return new Sub6DFakePlayerJoinDataNeededCommand();
                default:
                    return new UnknownSubCommand6DCommand();
            }
        }
    }
}