using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma;

namespace Booma
{
	[AutoGeneratedWireMessageImplementationAttribute]
	public partial class BlockGameJoinEventPayload
	{
		public override Type SerializableType => typeof(BlockGameJoinEventPayload);
		public override PSOBBGamePacketPayloadServer Read(Span<byte> buffer, ref int offset)
		{
			BlockGameJoinEventPayload_Serializer.Instance.InternalRead(this, buffer, ref offset);
			return this;
		}

		public override void Write(PSOBBGamePacketPayloadServer value, Span<byte> buffer, ref int offset)
		{
			BlockGameJoinEventPayload_Serializer.Instance.InternalWrite(this, buffer, ref offset);
		}
	}
}

namespace FreecraftCore.Serializer
{
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	//THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
	/// <summary>
	/// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
	/// code for the Type: <see cref = "BlockGameJoinEventPayload"/>
	/// </summary>
	public sealed partial class BlockGameJoinEventPayload_Serializer : BaseAutoGeneratedSerializerStrategy<BlockGameJoinEventPayload_Serializer, BlockGameJoinEventPayload>
	{
		/// <summary>
		/// Auto-generated deserialization/read method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalRead(BlockGameJoinEventPayload value, Span<byte> buffer, ref int offset)
		{
			//Type: PSOBBGamePacketPayloadServer Field: 1 Name: OperationCode Type: GameNetworkOperationCode
			;
			value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<GameNetworkOperationCode, Int16>.Instance.Read(buffer, ref offset);
			//Type: PSOBBGamePacketPayloadServer Field: 2 Name: Flags Type: Byte[]
			;
			if (value.isFlagsSerialized)
			value.Flags = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_4>.Instance.Read(buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 1 Name: PlayerCount Type: Int32
			;
			value.PlayerCount = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 2 Name: Maps Type: UInt32[]
			;
			value.Maps = FixedSizePrimitiveArrayTypeSerializerStrategy<uint, StaticTypedNumeric_Int32_32>.Instance.Read(buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 3 Name: _Players Type: PlayerInformationHeader[]
			;
			value._Players = FixedSizeComplexArrayTypeSerializerStrategy<PlayerInformationHeader_Serializer, PlayerInformationHeader, StaticTypedNumeric_Int32_4>.Instance.Read(buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 4 Name: Identifier Type: Byte
			;
			value.Identifier = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 5 Name: LeaderId Type: Byte
			;
			value.LeaderId = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 6 Name: One Type: Byte
			;
			value.One = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 7 Name: Settings Type: GameSettings
			;
			value.Settings = GameSettings_Serializer.Instance.Read(buffer, ref offset);
		}

		/// <summary>
		/// Auto-generated serialization/write method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalWrite(BlockGameJoinEventPayload value, Span<byte> buffer, ref int offset)
		{
			//Type: PSOBBGamePacketPayloadServer Field: 1 Name: OperationCode Type: GameNetworkOperationCode
			;
			GenericPrimitiveEnumTypeSerializerStrategy<GameNetworkOperationCode, Int16>.Instance.Write(value.OperationCode, buffer, ref offset);
			//Type: PSOBBGamePacketPayloadServer Field: 2 Name: Flags Type: Byte[]
			;
			if (value.isFlagsSerialized)
			FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_4>.Instance.Write(value.Flags, buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 1 Name: PlayerCount Type: Int32
			;
			GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.PlayerCount, buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 2 Name: Maps Type: UInt32[]
			;
			FixedSizePrimitiveArrayTypeSerializerStrategy<uint, StaticTypedNumeric_Int32_32>.Instance.Write(value.Maps, buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 3 Name: _Players Type: PlayerInformationHeader[]
			;
			FixedSizeComplexArrayTypeSerializerStrategy<PlayerInformationHeader_Serializer, PlayerInformationHeader, StaticTypedNumeric_Int32_4>.Instance.Write(value._Players, buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 4 Name: Identifier Type: Byte
			;
			BytePrimitiveSerializerStrategy.Instance.Write(value.Identifier, buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 5 Name: LeaderId Type: Byte
			;
			BytePrimitiveSerializerStrategy.Instance.Write(value.LeaderId, buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 6 Name: One Type: Byte
			;
			BytePrimitiveSerializerStrategy.Instance.Write(value.One, buffer, ref offset);
			//Type: BlockGameJoinEventPayload Field: 7 Name: Settings Type: GameSettings
			;
			GameSettings_Serializer.Instance.Write(value.Settings, buffer, ref offset);
		}

		private sealed class StaticTypedNumeric_Int32_32 : StaticTypedNumeric<Int32>
		{
			public sealed override Int32 Value => 32;
		}

		private sealed class StaticTypedNumeric_Int32_4 : StaticTypedNumeric<Int32>
		{
			public sealed override Int32 Value => 4;
		}
	}
}