using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma;

namespace Booma
{
	[AutoGeneratedWireMessageImplementationAttribute]
	public partial class CharacterCharacterSelectionAckPayload
	{
		public override Type SerializableType => typeof(CharacterCharacterSelectionAckPayload);
		public override PSOBBGamePacketPayloadServer Read(Span<byte> buffer, ref int offset)
		{
			CharacterCharacterSelectionAckPayload_Serializer.Instance.InternalRead(this, buffer, ref offset);
			return this;
		}

		public override void Write(PSOBBGamePacketPayloadServer value, Span<byte> buffer, ref int offset)
		{
			CharacterCharacterSelectionAckPayload_Serializer.Instance.InternalWrite(this, buffer, ref offset);
		}
	}
}

namespace FreecraftCore.Serializer
{
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	//THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
	/// <summary>
	/// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
	/// code for the Type: <see cref = "CharacterCharacterSelectionAckPayload"/>
	/// </summary>
	public sealed partial class CharacterCharacterSelectionAckPayload_Serializer : BaseAutoGeneratedSerializerStrategy<CharacterCharacterSelectionAckPayload_Serializer, CharacterCharacterSelectionAckPayload>
	{
		/// <summary>
		/// Auto-generated deserialization/read method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalRead(CharacterCharacterSelectionAckPayload value, Span<byte> buffer, ref int offset)
		{
			//Type: PSOBBGamePacketPayloadServer Field: 1 Name: OperationCode Type: GameNetworkOperationCode
			;
			value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<GameNetworkOperationCode, Int16>.Instance.Read(buffer, ref offset);
			//Type: PSOBBGamePacketPayloadServer Field: 2 Name: Flags Type: Byte[]
			;
			if (value.isFlagsSerialized)
			value.Flags = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_4>.Instance.Read(buffer, ref offset);
			//Type: CharacterCharacterSelectionAckPayload Field: 1 Name: Slot Type: Int32
			;
			value.Slot = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
			//Type: CharacterCharacterSelectionAckPayload Field: 2 Name: AckType Type: CharacterSelectionAckType
			;
			value.AckType = GenericPrimitiveEnumTypeSerializerStrategy<CharacterSelectionAckType, Int32>.Instance.Read(buffer, ref offset);
		}

		/// <summary>
		/// Auto-generated serialization/write method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalWrite(CharacterCharacterSelectionAckPayload value, Span<byte> buffer, ref int offset)
		{
			//Type: PSOBBGamePacketPayloadServer Field: 1 Name: OperationCode Type: GameNetworkOperationCode
			;
			GenericPrimitiveEnumTypeSerializerStrategy<GameNetworkOperationCode, Int16>.Instance.Write(value.OperationCode, buffer, ref offset);
			//Type: PSOBBGamePacketPayloadServer Field: 2 Name: Flags Type: Byte[]
			;
			if (value.isFlagsSerialized)
			FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_4>.Instance.Write(value.Flags, buffer, ref offset);
			//Type: CharacterCharacterSelectionAckPayload Field: 1 Name: Slot Type: Int32
			;
			GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.Slot, buffer, ref offset);
			//Type: CharacterCharacterSelectionAckPayload Field: 2 Name: AckType Type: CharacterSelectionAckType
			;
			GenericPrimitiveEnumTypeSerializerStrategy<CharacterSelectionAckType, Int32>.Instance.Write(value.AckType, buffer, ref offset);
		}

		private sealed class StaticTypedNumeric_Int32_4 : StaticTypedNumeric<Int32>
		{
			public sealed override Int32 Value => 4;
		}
	}
}