using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma;
namespace Booma
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class PSOBBGamePacketPayloadClient : IWireMessage<PSOBBGamePacketPayloadClient>
    {
        public virtual Type SerializableType => typeof(PSOBBGamePacketPayloadClient);
        public virtual PSOBBGamePacketPayloadClient Read(Span<byte> buffer, ref int offset)
        {
            PSOBBGamePacketPayloadClient_Serializer.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public virtual void Write(PSOBBGamePacketPayloadClient value, Span<byte> buffer, ref int offset)
        {
            PSOBBGamePacketPayloadClient_Serializer.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="PSOBBGamePacketPayloadClient"/>
    /// </summary>
    public sealed partial class PSOBBGamePacketPayloadClient_Serializer
            : BasePolymorphicAutoGeneratedSerializerStrategy<PSOBBGamePacketPayloadClient_Serializer, PSOBBGamePacketPayloadClient, UInt16>
    {
        protected override PSOBBGamePacketPayloadClient CreateType(int key)
        {
            switch (key)
            {
                case (int)Booma.GameNetworkOperationCode.BLOCK_SET_CHAR_DATA_TYPE:
                    return new BlockCharacterDataInitializeClientResponsePayload();
                case (int)Booma.GameNetworkOperationCode.PING_TYPE:
                    return new BlockClientPingResponsePayload();
                case (int)Booma.GameNetworkOperationCode.DONE_BURSTING_TYPE:
                    return new BlockFinishedGameBurstingRequestPayload();
                case (int)Booma.GameNetworkOperationCode.GAME_LIST_TYPE:
                    return new BlockGameListRequestPayload();
                case (int)Booma.GameNetworkOperationCode.LOBBY_CHANGE_TYPE:
                    return new BlockLobbyChangeRequestPayload();
                case (int)Booma.GameNetworkOperationCode.GAME_COMMAND0_TYPE:
                    return new BlockNetworkCommand60EventClientPayload();
                case (int)Booma.GameNetworkOperationCode.GAME_COMMAND2_TYPE:
                    return new BlockNetworkCommand62EventClientPayload();
                case (int)Booma.GameNetworkOperationCode.GAME_COMMANDD_TYPE:
                    return new BlockNetworkCommand6DEventClientPayload();
                case (int)Booma.GameNetworkOperationCode.GAME_CREATE_TYPE:
                    return new BlockPlayerCreateGameRequestPayload();
                case (int)Booma.GameNetworkOperationCode.CHAT_TYPE:
                    return new BlockTextChatMessageRequestPayload();
                case (int)Booma.GameNetworkOperationCode.BB_CHARACTER_SELECT_TYPE:
                    return new CharacterCharacterSelectionRequestPayload();
                case (int)Booma.GameNetworkOperationCode.BB_CHECKSUM_TYPE:
                    return new CharacterChecksumRequestPayload();
                case (int)Booma.GameNetworkOperationCode.BB_CHARACTER_UPDATE_TYPE:
                    return new CharacterCreationRequestPayload();
                case (int)Booma.GameNetworkOperationCode.BB_PARAM_CHUNK_REQ_TYPE:
                    return new CharacterDataParametersChunkRequestPayload();
                case (int)Booma.GameNetworkOperationCode.BB_PARAM_HEADER_REQ_TYPE:
                    return new CharacterDataParametersHeaderRequestPayload();
                case (int)Booma.GameNetworkOperationCode.BB_GUILDCARD_CHUNK_REQ_TYPE:
                    return new CharacterGuildCardChunkRequestPayload();
                case (int)Booma.GameNetworkOperationCode.BB_GUILD_REQUEST_TYPE:
                    return new CharacterGuildHeaderRequestPayload();
                case (int)Booma.GameNetworkOperationCode.BB_OPTION_REQUEST_TYPE:
                    return new CharacterOptionsRequestPayload();
                case (int)Booma.GameNetworkOperationCode.BB_OPTION_CONFIG_TYPE:
                    return new CharacterOptionsUpdateRequestPayload();
                case (int)Booma.GameNetworkOperationCode.TYPE_05:
                    return new SharedDisconnectionRequestPayload();
                case (int)Booma.GameNetworkOperationCode.LOGIN_93_TYPE:
                    return new SharedLoginRequest93Payload();
                case (int)Booma.GameNetworkOperationCode.MENU_SELECT_TYPE:
                    return new SharedMenuSelectionRequestPayload();
                default:
                    return new UnknownClientGamePayload();
            }
        }
    }
}