using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma.Proxy;
namespace Booma.Proxy
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class SharedLoginRequest93Payload
    {
        public override Type SerializableType => typeof(SharedLoginRequest93Payload);
        public override PSOBBGamePacketPayloadClient Read(Span<byte> buffer, ref int offset)
        {
            SharedLoginRequest93Payload_Serializer.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(PSOBBGamePacketPayloadClient value, Span<byte> buffer, ref int offset)
        {
            SharedLoginRequest93Payload_Serializer.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SharedLoginRequest93Payload"/>
    /// </summary>
    public sealed partial class SharedLoginRequest93Payload_Serializer
            : BaseAutoGeneratedSerializerStrategy<SharedLoginRequest93Payload_Serializer, SharedLoginRequest93Payload>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SharedLoginRequest93Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: PSOBBGamePacketPayloadClient Field: 1 Name: OperationCode Type: GameNetworkOperationCode;
            value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<GameNetworkOperationCode, UInt16>.Instance.Read(buffer, ref offset);
            //Type: PSOBBGamePacketPayloadClient Field: 2 Name: Flags Type: Byte[];
            if (value.isFlagsSerialized)value.Flags = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_4>.Instance.Read(buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 1 Name: Tag Type: Int32;
            value.Tag = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 2 Name: GuildCardId Type: UInt32;
            value.GuildCardId = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 3 Name: ClientVersion Type: UInt16;
            value.ClientVersion = GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Read(buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 4 Name: unk2 Type: Byte[];
            value.unk2 = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_6>.Instance.Read(buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 5 Name: TeamId Type: Int32;
            value.TeamId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 6 Name: UserName Type: String;
            value.UserName = FixedSizeStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, StaticTypedNumeric_Int32_15, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 7 Name: unused1 Type: Byte[];
            value.unused1 = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_32>.Instance.Read(buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 8 Name: Password Type: String;
            value.Password = FixedSizeStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, StaticTypedNumeric_Int32_15, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 9 Name: unused2 Type: Byte[];
            value.unused2 = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_40>.Instance.Read(buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 10 Name: ClientData Type: ClientVerificationData;
            value.ClientData = ClientVerificationData_Serializer.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SharedLoginRequest93Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: PSOBBGamePacketPayloadClient Field: 1 Name: OperationCode Type: GameNetworkOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<GameNetworkOperationCode, UInt16>.Instance.Write(value.OperationCode, buffer, ref offset);
            //Type: PSOBBGamePacketPayloadClient Field: 2 Name: Flags Type: Byte[];
            if (value.isFlagsSerialized)FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_4>.Instance.Write(value.Flags, buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 1 Name: Tag Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.Tag, buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 2 Name: GuildCardId Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.GuildCardId, buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 3 Name: ClientVersion Type: UInt16;
            GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Write(value.ClientVersion, buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 4 Name: unk2 Type: Byte[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_6>.Instance.Write(value.unk2, buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 5 Name: TeamId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.TeamId, buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 6 Name: UserName Type: String;
            FixedSizeStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, StaticTypedNumeric_Int32_15, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.UserName, buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 7 Name: unused1 Type: Byte[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_32>.Instance.Write(value.unused1, buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 8 Name: Password Type: String;
            FixedSizeStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, StaticTypedNumeric_Int32_15, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.Password, buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 9 Name: unused2 Type: Byte[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_40>.Instance.Write(value.unused2, buffer, ref offset);
            //Type: SharedLoginRequest93Payload Field: 10 Name: ClientData Type: ClientVerificationData;
            ClientVerificationData_Serializer.Instance.Write(value.ClientData, buffer, ref offset);
        }
        private sealed class StaticTypedNumeric_Int32_6 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 6; }
        private sealed class StaticTypedNumeric_Int32_15 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 15; }
        private sealed class StaticTypedNumeric_Int32_32 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 32; }
        private sealed class StaticTypedNumeric_Int32_40 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 40; }
        private sealed class StaticTypedNumeric_Int32_4 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 4; }
    }
}