using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma;

namespace Booma
{
	[AutoGeneratedWireMessageImplementationAttribute]
	public partial class PatchingFileCheckRequestPayload
	{
		public override Type SerializableType => typeof(PatchingFileCheckRequestPayload);
		public override PSOBBPatchPacketPayloadServer Read(Span<byte> buffer, ref int offset)
		{
			PatchingFileCheckRequestPayload_Serializer.Instance.InternalRead(this, buffer, ref offset);
			return this;
		}

		public override void Write(PSOBBPatchPacketPayloadServer value, Span<byte> buffer, ref int offset)
		{
			PatchingFileCheckRequestPayload_Serializer.Instance.InternalWrite(this, buffer, ref offset);
		}
	}
}

namespace FreecraftCore.Serializer
{
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	//THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
	/// <summary>
	/// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
	/// code for the Type: <see cref = "PatchingFileCheckRequestPayload"/>
	/// </summary>
	public sealed partial class PatchingFileCheckRequestPayload_Serializer : BaseAutoGeneratedSerializerStrategy<PatchingFileCheckRequestPayload_Serializer, PatchingFileCheckRequestPayload>
	{
		/// <summary>
		/// Auto-generated deserialization/read method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalRead(PatchingFileCheckRequestPayload value, Span<byte> buffer, ref int offset)
		{
			//Type: PSOBBPatchPacketPayloadServer Field: 1 Name: OperationCode Type: PatchNetworkOperationCode
			;
			value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<PatchNetworkOperationCode, Int16>.Instance.Read(buffer, ref offset);
			//Type: PatchingFileCheckRequestPayload Field: 1 Name: PatchFileIndex Type: Int32
			;
			value.PatchFileIndex = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
			//Type: PatchingFileCheckRequestPayload Field: 2 Name: PatchFileName Type: String
			;
			value.PatchFileName = FixedSizeStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, StaticTypedNumeric_Int32_32, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset);
		}

		/// <summary>
		/// Auto-generated serialization/write method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalWrite(PatchingFileCheckRequestPayload value, Span<byte> buffer, ref int offset)
		{
			//Type: PSOBBPatchPacketPayloadServer Field: 1 Name: OperationCode Type: PatchNetworkOperationCode
			;
			GenericPrimitiveEnumTypeSerializerStrategy<PatchNetworkOperationCode, Int16>.Instance.Write(value.OperationCode, buffer, ref offset);
			//Type: PatchingFileCheckRequestPayload Field: 1 Name: PatchFileIndex Type: Int32
			;
			GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.PatchFileIndex, buffer, ref offset);
			//Type: PatchingFileCheckRequestPayload Field: 2 Name: PatchFileName Type: String
			;
			FixedSizeStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, StaticTypedNumeric_Int32_32, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.PatchFileName, buffer, ref offset);
		}

		private sealed class StaticTypedNumeric_Int32_32 : StaticTypedNumeric<Int32>
		{
			public sealed override Int32 Value => 32;
		}
	}
}