using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma.Proxy;
namespace Booma.Proxy
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class PatchingRedirectPayload
    {
        public override Type SerializableType => typeof(PatchingRedirectPayload);
        public override PSOBBPatchPacketPayloadServer Read(Span<byte> buffer, ref int offset)
        {
            PatchingRedirectPayload_Serializer.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(PSOBBPatchPacketPayloadServer value, Span<byte> buffer, ref int offset)
        {
            PatchingRedirectPayload_Serializer.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="PatchingRedirectPayload"/>
    /// </summary>
    public sealed partial class PatchingRedirectPayload_Serializer
            : BaseAutoGeneratedSerializerStrategy<PatchingRedirectPayload_Serializer, PatchingRedirectPayload>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(PatchingRedirectPayload value, Span<byte> buffer, ref int offset)
        {
            //Type: PSOBBPatchPacketPayloadServer Field: 1 Name: OperationCode Type: PatchNetworkOperationCode;
            value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<PatchNetworkOperationCode, Int16>.Instance.Read(buffer, ref offset);
            //Type: PatchingRedirectPayload Field: 1 Name: IPAddress Type: Byte[];
            value.IPAddress = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_4>.Instance.Read(buffer, ref offset);
            //Type: PatchingRedirectPayload Field: 2 Name: Port Type: UInt16;
            value.Port = BigEndianGenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(PatchingRedirectPayload value, Span<byte> buffer, ref int offset)
        {
            //Type: PSOBBPatchPacketPayloadServer Field: 1 Name: OperationCode Type: PatchNetworkOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<PatchNetworkOperationCode, Int16>.Instance.Write(value.OperationCode, buffer, ref offset);
            //Type: PatchingRedirectPayload Field: 1 Name: IPAddress Type: Byte[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_4>.Instance.Write(value.IPAddress, buffer, ref offset);
            //Type: PatchingRedirectPayload Field: 2 Name: Port Type: UInt16;
            BigEndianGenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Write(value.Port, buffer, ref offset);
        }
        private sealed class StaticTypedNumeric_Int32_4 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 4; }
    }
}