using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma.Proxy;

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="CharacterSpecialCustomInfo"/>
    /// </summary>
    public sealed partial class CharacterSpecialCustomInfo_AutoGeneratedTemplateSerializerStrategy
            : BaseAutoGeneratedSerializerStrategy<CharacterSpecialCustomInfo_AutoGeneratedTemplateSerializerStrategy, CharacterSpecialCustomInfo>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(CharacterSpecialCustomInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: CharacterSpecialCustomInfo Field: 1 Name: NameColor Type: UInt32;
            value.NameColor = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: CharacterSpecialCustomInfo Field: 2 Name: ModelType Type: CharacterModelType;
            value.ModelType = GenericPrimitiveEnumTypeSerializerStrategy<CharacterModelType, Byte>.Instance.Read(buffer, ref offset);
            //Type: CharacterSpecialCustomInfo Field: 3 Name: unused Type: Byte[];
            value.unused = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_15>.Instance.Read(buffer, ref offset);
            //Type: CharacterSpecialCustomInfo Field: 4 Name: ColoredNameChecksum Type: UInt32;
            value.ColoredNameChecksum = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(CharacterSpecialCustomInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: CharacterSpecialCustomInfo Field: 1 Name: NameColor Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.NameColor, buffer, ref offset);
            //Type: CharacterSpecialCustomInfo Field: 2 Name: ModelType Type: CharacterModelType;
            GenericPrimitiveEnumTypeSerializerStrategy<CharacterModelType, Byte>.Instance.Write(value.ModelType, buffer, ref offset);
            //Type: CharacterSpecialCustomInfo Field: 3 Name: unused Type: Byte[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_15>.Instance.Write(value.unused, buffer, ref offset);
            //Type: CharacterSpecialCustomInfo Field: 4 Name: ColoredNameChecksum Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.ColoredNameChecksum, buffer, ref offset);
        }
        private sealed class StaticTypedNumeric_Int32_15 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 15; }
    }
}