using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma.Proxy;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="HairColorInfo"/>
    /// </summary>
    public sealed partial class HairColorInfo_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<HairColorInfo_AutoGeneratedTemplateSerializerStrategy, HairColorInfo>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(HairColorInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: HairColorInfo Field: 1 Name: Color Type: Vector3;
            value.Color = Vector3_UInt16_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(HairColorInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: HairColorInfo Field: 1 Name: Color Type: Vector3;
            Vector3_UInt16_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.Color, buffer, ref offset);
        }
    }
}