using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma.Proxy;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="Vector3<UInt16>"/>
    /// </summary>
    public sealed partial class Vector3_UInt16_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<Vector3_UInt16_AutoGeneratedTemplateSerializerStrategy, Vector3<UInt16>>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(Vector3<UInt16> value, Span<byte> buffer, ref int offset)
        {
            //Type: Vector2 Field: 1 Name: X Type: UInt16;
            value.X = GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Read(buffer, ref offset);
            //Type: Vector2 Field: 2 Name: Y Type: UInt16;
            value.Y = GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Read(buffer, ref offset);
            //Type: Vector3 Field: 1 Name: Z Type: UInt16;
            value.Z = GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(Vector3<UInt16> value, Span<byte> buffer, ref int offset)
        {
            //Type: Vector2 Field: 1 Name: X Type: UInt16;
            GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Write(value.X, buffer, ref offset);
            //Type: Vector2 Field: 2 Name: Y Type: UInt16;
            GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Write(value.Y, buffer, ref offset);
            //Type: Vector3 Field: 1 Name: Z Type: UInt16;
            GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Write(value.Z, buffer, ref offset);
        }
    }
}