using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="MapDatFormatTableEntryHeader"/>
    /// </summary>
    public sealed partial class MapDatFormatTableEntryHeader_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<MapDatFormatTableEntryHeader_AutoGeneratedTemplateSerializerStrategy, MapDatFormatTableEntryHeader>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(MapDatFormatTableEntryHeader value, Span<byte> buffer, ref int offset)
        {
            //Type: MapDatFormatTableEntryHeader Field: 1 Name: EntryTotalSize Type: UInt32;
            value.EntryTotalSize = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: MapDatFormatTableEntryHeader Field: 2 Name: Area Type: UInt32;
            value.Area = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: MapDatFormatTableEntryHeader Field: 3 Name: EntryBodySize Type: UInt32;
            value.EntryBodySize = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(MapDatFormatTableEntryHeader value, Span<byte> buffer, ref int offset)
        {
            //Type: MapDatFormatTableEntryHeader Field: 1 Name: EntryTotalSize Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.EntryTotalSize, buffer, ref offset);
            //Type: MapDatFormatTableEntryHeader Field: 2 Name: Area Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.Area, buffer, ref offset);
            //Type: MapDatFormatTableEntryHeader Field: 3 Name: EntryBodySize Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.EntryBodySize, buffer, ref offset);
        }
    }
}