using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma;
namespace Booma
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class MapDatFormatTableEntryContainer : IWireMessage<MapDatFormatTableEntryContainer>
    {
        public virtual Type SerializableType => typeof(MapDatFormatTableEntryContainer);
        public virtual MapDatFormatTableEntryContainer Read(Span<byte> buffer, ref int offset)
        {
            MapDatFormatTableEntryContainer_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public virtual void Write(MapDatFormatTableEntryContainer value, Span<byte> buffer, ref int offset)
        {
            MapDatFormatTableEntryContainer_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="MapDatFormatTableEntryContainer"/>
    /// </summary>
    public sealed partial class MapDatFormatTableEntryContainer_AutoGeneratedTemplateSerializerStrategy
        : BasePolymorphicAutoGeneratedSerializerStrategy<MapDatFormatTableEntryContainer_AutoGeneratedTemplateSerializerStrategy, MapDatFormatTableEntryContainer, Int32>
    {
        protected override MapDatFormatTableEntryContainer CreateType(int key)
        {
            switch (key)
            {
                case 1:
                    return new MapDataFormatObjectEntryContainer();
                default:
                    throw new NotImplementedException($"Encountered unimplemented sub-type for Type: {nameof(MapDatFormatTableEntryContainer)} with Key: {key}");
            }
        }
    }
}