using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="NRelSectionModel"/>
    /// </summary>
    public sealed partial class NRelSectionModel_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<NRelSectionModel_AutoGeneratedTemplateSerializerStrategy, NRelSectionModel>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(NRelSectionModel value, Span<byte> buffer, ref int offset)
        {
            //Type: NRelSectionModel Field: 1 Name: SecionId Type: UInt32;
            value.SecionId = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: NRelSectionModel Field: 2 Name: Position Type: Vector3;
            value.Position = Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: NRelSectionModel Field: 3 Name: unk1 Type: Int32;
            value.unk1 = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: NRelSectionModel Field: 4 Name: YRotation Type: UInt32;
            value.YRotation = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: NRelSectionModel Field: 5 Name: unk2 Type: Int32;
            value.unk2 = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: NRelSectionModel Field: 6 Name: unk3 Type: Single;
            value.unk3 = GenericTypePrimitiveSerializerStrategy<Single>.Instance.Read(buffer, ref offset);
            //Type: NRelSectionModel Field: 7 Name: SimpleGeometryPointer Type: UInt32;
            value.SimpleGeometryPointer = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: NRelSectionModel Field: 8 Name: AnimatedGeometryPointer Type: UInt32;
            value.AnimatedGeometryPointer = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: NRelSectionModel Field: 9 Name: SimpleGeometryCount Type: UInt32;
            value.SimpleGeometryCount = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: NRelSectionModel Field: 10 Name: AnimatedGeometryCount Type: UInt32;
            value.AnimatedGeometryCount = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: NRelSectionModel Field: 11 Name: unk4 Type: Int32;
            value.unk4 = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(NRelSectionModel value, Span<byte> buffer, ref int offset)
        {
            //Type: NRelSectionModel Field: 1 Name: SecionId Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.SecionId, buffer, ref offset);
            //Type: NRelSectionModel Field: 2 Name: Position Type: Vector3;
            Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.Position, buffer, ref offset);
            //Type: NRelSectionModel Field: 3 Name: unk1 Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.unk1, buffer, ref offset);
            //Type: NRelSectionModel Field: 4 Name: YRotation Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.YRotation, buffer, ref offset);
            //Type: NRelSectionModel Field: 5 Name: unk2 Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.unk2, buffer, ref offset);
            //Type: NRelSectionModel Field: 6 Name: unk3 Type: Single;
            GenericTypePrimitiveSerializerStrategy<Single>.Instance.Write(value.unk3, buffer, ref offset);
            //Type: NRelSectionModel Field: 7 Name: SimpleGeometryPointer Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.SimpleGeometryPointer, buffer, ref offset);
            //Type: NRelSectionModel Field: 8 Name: AnimatedGeometryPointer Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.AnimatedGeometryPointer, buffer, ref offset);
            //Type: NRelSectionModel Field: 9 Name: SimpleGeometryCount Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.SimpleGeometryCount, buffer, ref offset);
            //Type: NRelSectionModel Field: 10 Name: AnimatedGeometryCount Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.AnimatedGeometryCount, buffer, ref offset);
            //Type: NRelSectionModel Field: 11 Name: unk4 Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.unk4, buffer, ref offset);
        }
    }
}