using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="NRelMainBlockModel"/>
    /// </summary>
    public sealed partial class NRelMainBlockModel_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<NRelMainBlockModel_AutoGeneratedTemplateSerializerStrategy, NRelMainBlockModel>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(NRelMainBlockModel value, Span<byte> buffer, ref int offset)
        {
            //Type: NRelMainBlockModel Field: 1 Name: unk1 Type: Int64;
            value.unk1 = GenericTypePrimitiveSerializerStrategy<Int64>.Instance.Read(buffer, ref offset);
            //Type: NRelMainBlockModel Field: 2 Name: SectionCount Type: UInt32;
            value.SectionCount = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: NRelMainBlockModel Field: 3 Name: unk2 Type: Int32;
            value.unk2 = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: NRelMainBlockModel Field: 4 Name: SectionPointer Type: UInt32;
            value.SectionPointer = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: NRelMainBlockModel Field: 5 Name: TextureNamePointer Type: UInt32;
            value.TextureNamePointer = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(NRelMainBlockModel value, Span<byte> buffer, ref int offset)
        {
            //Type: NRelMainBlockModel Field: 1 Name: unk1 Type: Int64;
            GenericTypePrimitiveSerializerStrategy<Int64>.Instance.Write(value.unk1, buffer, ref offset);
            //Type: NRelMainBlockModel Field: 2 Name: SectionCount Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.SectionCount, buffer, ref offset);
            //Type: NRelMainBlockModel Field: 3 Name: unk2 Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.unk2, buffer, ref offset);
            //Type: NRelMainBlockModel Field: 4 Name: SectionPointer Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.SectionPointer, buffer, ref offset);
            //Type: NRelMainBlockModel Field: 5 Name: TextureNamePointer Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.TextureNamePointer, buffer, ref offset);
        }
    }
}