using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma.Proxy;
namespace Booma.Proxy
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class CharacterOptionsResponsePayload
    {
        public override Type SerializableType => typeof(CharacterOptionsResponsePayload);
        public override PSOBBGamePacketPayloadServer Read(Span<byte> buffer, ref int offset)
        {
            CharacterOptionsResponsePayload_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(PSOBBGamePacketPayloadServer value, Span<byte> buffer, ref int offset)
        {
            CharacterOptionsResponsePayload_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="CharacterOptionsResponsePayload"/>
    /// </summary>
    public sealed partial class CharacterOptionsResponsePayload_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<CharacterOptionsResponsePayload_AutoGeneratedTemplateSerializerStrategy, CharacterOptionsResponsePayload>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(CharacterOptionsResponsePayload value, Span<byte> buffer, ref int offset)
        {
            //Type: PSOBBGamePacketPayloadServer Field: 1 Name: OperationCode Type: GameNetworkOperationCode;
            value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<GameNetworkOperationCode, Int16>.Instance.Read(buffer, ref offset);
            //Type: PSOBBGamePacketPayloadServer Field: 2 Name: Flags Type: Byte[];
            if (value.isFlagsSerialized)value.Flags = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_4>.Instance.Read(buffer, ref offset);
            //Type: CharacterOptionsResponsePayload Field: 1 Name: unk Type: Byte[];
            value.unk = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_276>.Instance.Read(buffer, ref offset);
            //Type: CharacterOptionsResponsePayload Field: 2 Name: Bindings Type: BindingsConfig;
            value.Bindings = BindingsConfig_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: CharacterOptionsResponsePayload Field: 3 Name: GuildCard Type: UInt32;
            value.GuildCard = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: CharacterOptionsResponsePayload Field: 4 Name: TeamInfo Type: AccountTeamInformation;
            value.TeamInfo = AccountTeamInformation_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(CharacterOptionsResponsePayload value, Span<byte> buffer, ref int offset)
        {
            //Type: PSOBBGamePacketPayloadServer Field: 1 Name: OperationCode Type: GameNetworkOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<GameNetworkOperationCode, Int16>.Instance.Write(value.OperationCode, buffer, ref offset);
            //Type: PSOBBGamePacketPayloadServer Field: 2 Name: Flags Type: Byte[];
            if (value.isFlagsSerialized)FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_4>.Instance.Write(value.Flags, buffer, ref offset);
            //Type: CharacterOptionsResponsePayload Field: 1 Name: unk Type: Byte[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_276>.Instance.Write(value.unk, buffer, ref offset);
            //Type: CharacterOptionsResponsePayload Field: 2 Name: Bindings Type: BindingsConfig;
            BindingsConfig_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.Bindings, buffer, ref offset);
            //Type: CharacterOptionsResponsePayload Field: 3 Name: GuildCard Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.GuildCard, buffer, ref offset);
            //Type: CharacterOptionsResponsePayload Field: 4 Name: TeamInfo Type: AccountTeamInformation;
            AccountTeamInformation_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.TeamInfo, buffer, ref offset);
        }
        private sealed class StaticTypedNumeric_Int32_276 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 276; }
        private sealed class StaticTypedNumeric_Int32_4 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 4; }
    }
}