using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma.Proxy;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="ClientVerificationData"/>
    /// </summary>
    public sealed partial class ClientVerificationData_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<ClientVerificationData_AutoGeneratedTemplateSerializerStrategy, ClientVerificationData>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(ClientVerificationData value, Span<byte> buffer, ref int offset)
        {
            //Type: ClientVerificationData Field: 9 Name: HardwareInformation Type: Int64;
            value.HardwareInformation = GenericTypePrimitiveSerializerStrategy<Int64>.Instance.Read(buffer, ref offset);
            //Type: ClientVerificationData Field: 10 Name: SecurityData Type: Byte[];
            value.SecurityData = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_40>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(ClientVerificationData value, Span<byte> buffer, ref int offset)
        {
            //Type: ClientVerificationData Field: 9 Name: HardwareInformation Type: Int64;
            GenericTypePrimitiveSerializerStrategy<Int64>.Instance.Write(value.HardwareInformation, buffer, ref offset);
            //Type: ClientVerificationData Field: 10 Name: SecurityData Type: Byte[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_40>.Instance.Write(value.SecurityData, buffer, ref offset);
        }
        private sealed class StaticTypedNumeric_Int32_40 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 40; }
    }
}