using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma.Proxy;
namespace Booma.Proxy
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class Sub60FinishedWarpAckCommand
    {
        public override Type SerializableType => typeof(Sub60FinishedWarpAckCommand);
        public override BaseSubCommand60 Read(Span<byte> buffer, ref int offset)
        {
            Sub60FinishedWarpAckCommand_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(BaseSubCommand60 value, Span<byte> buffer, ref int offset)
        {
            Sub60FinishedWarpAckCommand_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="Sub60FinishedWarpAckCommand"/>
    /// </summary>
    public sealed partial class Sub60FinishedWarpAckCommand_AutoGeneratedTemplateSerializerStrategy
            : BaseAutoGeneratedSerializerStrategy<Sub60FinishedWarpAckCommand_AutoGeneratedTemplateSerializerStrategy, Sub60FinishedWarpAckCommand>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(Sub60FinishedWarpAckCommand value, Span<byte> buffer, ref int offset)
        {
            //Type: BaseSubCommand60 Field: 1 Name: CommandOperationCode Type: SubCommand60OperationCode;
            value.CommandOperationCode = GenericPrimitiveEnumTypeSerializerStrategy<SubCommand60OperationCode, Byte>.Instance.Read(buffer, ref offset);
            //Type: BaseSubCommand60 Field: 2 Name: CommandSize Type: Byte;
            if (value.isSizeSerialized)value.CommandSize = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: Sub60FinishedWarpAckCommand Field: 1 Name: Identifier Type: Byte;
            value.Identifier = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: Sub60FinishedWarpAckCommand Field: 2 Name: unusued Type: Byte;
            value.unusued = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: Sub60FinishedWarpAckCommand Field: 3 Name: ZoneId Type: Int32;
            value.ZoneId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: Sub60FinishedWarpAckCommand Field: 4 Name: Position Type: Vector3;
            value.Position = Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: Sub60FinishedWarpAckCommand Field: 5 Name: RawRotation Type: Int16;
            value.RawRotation = GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Read(buffer, ref offset);
            //Type: Sub60FinishedWarpAckCommand Field: 6 Name: unk Type: UInt16;
            value.unk = GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(Sub60FinishedWarpAckCommand value, Span<byte> buffer, ref int offset)
        {
            //Type: BaseSubCommand60 Field: 1 Name: CommandOperationCode Type: SubCommand60OperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<SubCommand60OperationCode, Byte>.Instance.Write(value.CommandOperationCode, buffer, ref offset);
            //Type: BaseSubCommand60 Field: 2 Name: CommandSize Type: Byte;
            if (value.isSizeSerialized)BytePrimitiveSerializerStrategy.Instance.Write(value.CommandSize, buffer, ref offset);
            //Type: Sub60FinishedWarpAckCommand Field: 1 Name: Identifier Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.Identifier, buffer, ref offset);
            //Type: Sub60FinishedWarpAckCommand Field: 2 Name: unusued Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.unusued, buffer, ref offset);
            //Type: Sub60FinishedWarpAckCommand Field: 3 Name: ZoneId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.ZoneId, buffer, ref offset);
            //Type: Sub60FinishedWarpAckCommand Field: 4 Name: Position Type: Vector3;
            Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.Position, buffer, ref offset);
            //Type: Sub60FinishedWarpAckCommand Field: 5 Name: RawRotation Type: Int16;
            GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Write(value.RawRotation, buffer, ref offset);
            //Type: Sub60FinishedWarpAckCommand Field: 6 Name: unk Type: UInt16;
            GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Write(value.unk, buffer, ref offset);
        }
    }
}