using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma.Proxy;
namespace Booma.Proxy
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class Sub62ClientBurstBeginEventCommand
    {
        public override Type SerializableType => typeof(Sub62ClientBurstBeginEventCommand);
        public override BaseSubCommand62 Read(Span<byte> buffer, ref int offset)
        {
            Sub62ClientBurstBeginEventCommand_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(BaseSubCommand62 value, Span<byte> buffer, ref int offset)
        {
            Sub62ClientBurstBeginEventCommand_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="Sub62ClientBurstBeginEventCommand"/>
    /// </summary>
    public sealed partial class Sub62ClientBurstBeginEventCommand_AutoGeneratedTemplateSerializerStrategy
            : BaseAutoGeneratedSerializerStrategy<Sub62ClientBurstBeginEventCommand_AutoGeneratedTemplateSerializerStrategy, Sub62ClientBurstBeginEventCommand>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(Sub62ClientBurstBeginEventCommand value, Span<byte> buffer, ref int offset)
        {
            //Type: BaseSubCommand62 Field: 1 Name: CommandOperationCode Type: SubCommand62OperationCode;
            value.CommandOperationCode = GenericPrimitiveEnumTypeSerializerStrategy<SubCommand62OperationCode, Byte>.Instance.Read(buffer, ref offset);
            //Type: BaseSubCommand62 Field: 2 Name: CommandSize Type: Byte;
            if (value.isSizeSerialized)value.CommandSize = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: Sub62ClientBurstBeginEventCommand Field: 1 Name: QuestData Type: Byte[];
            value.QuestData = PrimitiveArrayTypeSerializerStrategy<byte>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(Sub62ClientBurstBeginEventCommand value, Span<byte> buffer, ref int offset)
        {
            //Type: BaseSubCommand62 Field: 1 Name: CommandOperationCode Type: SubCommand62OperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<SubCommand62OperationCode, Byte>.Instance.Write(value.CommandOperationCode, buffer, ref offset);
            //Type: BaseSubCommand62 Field: 2 Name: CommandSize Type: Byte;
            if (value.isSizeSerialized)BytePrimitiveSerializerStrategy.Instance.Write(value.CommandSize, buffer, ref offset);
            //Type: Sub62ClientBurstBeginEventCommand Field: 1 Name: QuestData Type: Byte[];
            PrimitiveArrayTypeSerializerStrategy<byte>.Instance.Write(value.QuestData, buffer, ref offset);
        }
    }
}