using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma.Proxy;
namespace Booma.Proxy
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class Sub60ObjectDamageRecievedCommand
    {
        public override Type SerializableType => typeof(Sub60ObjectDamageRecievedCommand);
        public override BaseSubCommand60 Read(Span<byte> buffer, ref int offset)
        {
            Sub60ObjectDamageRecievedCommand_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(BaseSubCommand60 value, Span<byte> buffer, ref int offset)
        {
            Sub60ObjectDamageRecievedCommand_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="Sub60ObjectDamageRecievedCommand"/>
    /// </summary>
    public sealed partial class Sub60ObjectDamageRecievedCommand_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<Sub60ObjectDamageRecievedCommand_AutoGeneratedTemplateSerializerStrategy, Sub60ObjectDamageRecievedCommand>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(Sub60ObjectDamageRecievedCommand value, Span<byte> buffer, ref int offset)
        {
            //Type: BaseSubCommand60 Field: 1 Name: CommandOperationCode Type: SubCommand60OperationCode;
            value.CommandOperationCode = GenericPrimitiveEnumTypeSerializerStrategy<SubCommand60OperationCode, Byte>.Instance.Read(buffer, ref offset);
            //Type: BaseSubCommand60 Field: 2 Name: CommandSize Type: Byte;
            if (value.isSizeSerialized)value.CommandSize = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 1 Name: ObjectIdentifier Type: MapObjectIdentifier;
            value.ObjectIdentifier = MapObjectIdentifier_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 2 Name: ObjectIdentifier2 Type: Int16;
            value.ObjectIdentifier2 = GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Read(buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 3 Name: TotalDamageTaken Type: UInt16;
            value.TotalDamageTaken = GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Read(buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 4 Name: UnknownFlag1 Type: Byte;
            value.UnknownFlag1 = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 5 Name: UnknownFlag2 Type: DamageFlag2;
            value.UnknownFlag2 = GenericPrimitiveEnumTypeSerializerStrategy<DamageFlag2, Byte>.Instance.Read(buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 6 Name: UnknownFlag3 Type: DamageFlag3;
            value.UnknownFlag3 = GenericPrimitiveEnumTypeSerializerStrategy<DamageFlag3, Byte>.Instance.Read(buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 7 Name: UnknownFlag4 Type: Byte;
            value.UnknownFlag4 = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(Sub60ObjectDamageRecievedCommand value, Span<byte> buffer, ref int offset)
        {
            //Type: BaseSubCommand60 Field: 1 Name: CommandOperationCode Type: SubCommand60OperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<SubCommand60OperationCode, Byte>.Instance.Write(value.CommandOperationCode, buffer, ref offset);
            //Type: BaseSubCommand60 Field: 2 Name: CommandSize Type: Byte;
            if (value.isSizeSerialized)BytePrimitiveSerializerStrategy.Instance.Write(value.CommandSize, buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 1 Name: ObjectIdentifier Type: MapObjectIdentifier;
            MapObjectIdentifier_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.ObjectIdentifier, buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 2 Name: ObjectIdentifier2 Type: Int16;
            GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Write(value.ObjectIdentifier2, buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 3 Name: TotalDamageTaken Type: UInt16;
            GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Write(value.TotalDamageTaken, buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 4 Name: UnknownFlag1 Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.UnknownFlag1, buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 5 Name: UnknownFlag2 Type: DamageFlag2;
            GenericPrimitiveEnumTypeSerializerStrategy<DamageFlag2, Byte>.Instance.Write(value.UnknownFlag2, buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 6 Name: UnknownFlag3 Type: DamageFlag3;
            GenericPrimitiveEnumTypeSerializerStrategy<DamageFlag3, Byte>.Instance.Write(value.UnknownFlag3, buffer, ref offset);
            //Type: Sub60ObjectDamageRecievedCommand Field: 7 Name: UnknownFlag4 Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.UnknownFlag4, buffer, ref offset);
        }
    }
}