using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma.Proxy;
namespace Booma.Proxy
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class UnknownSubCommand6DCommand
    {
        public override Type SerializableType => typeof(UnknownSubCommand6DCommand);
        public override BaseSubCommand6D Read(Span<byte> buffer, ref int offset)
        {
            UnknownSubCommand6DCommand_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(BaseSubCommand6D value, Span<byte> buffer, ref int offset)
        {
            UnknownSubCommand6DCommand_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="UnknownSubCommand6DCommand"/>
    /// </summary>
    public sealed partial class UnknownSubCommand6DCommand_AutoGeneratedTemplateSerializerStrategy
            : BaseAutoGeneratedSerializerStrategy<UnknownSubCommand6DCommand_AutoGeneratedTemplateSerializerStrategy, UnknownSubCommand6DCommand>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(UnknownSubCommand6DCommand value, Span<byte> buffer, ref int offset)
        {
            //Type: BaseSubCommand6D Field: 1 Name: CommandOperationCode Type: SubCommand6DOperationCode;
            value.CommandOperationCode = GenericPrimitiveEnumTypeSerializerStrategy<SubCommand6DOperationCode, Byte>.Instance.Read(buffer, ref offset);
            //Type: BaseSubCommand6D Field: 2 Name: HeaderUnk1 Type: Byte;
            value.HeaderUnk1 = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: BaseSubCommand6D Field: 3 Name: OptionalIdentifier Type: Byte;
            value.OptionalIdentifier = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: BaseSubCommand6D Field: 4 Name: HeaderUnk3 Type: Byte;
            value.HeaderUnk3 = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: BaseSubCommand6D Field: 5 Name: CommandSize Type: Int32;
            value.CommandSize = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: UnknownSubCommand6DCommand Field: 1 Name: UnknownBytes Type: Byte[];
            value.UnknownBytes = PrimitiveArrayTypeSerializerStrategy<byte>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(UnknownSubCommand6DCommand value, Span<byte> buffer, ref int offset)
        {
            //Type: BaseSubCommand6D Field: 1 Name: CommandOperationCode Type: SubCommand6DOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<SubCommand6DOperationCode, Byte>.Instance.Write(value.CommandOperationCode, buffer, ref offset);
            //Type: BaseSubCommand6D Field: 2 Name: HeaderUnk1 Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.HeaderUnk1, buffer, ref offset);
            //Type: BaseSubCommand6D Field: 3 Name: OptionalIdentifier Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.OptionalIdentifier, buffer, ref offset);
            //Type: BaseSubCommand6D Field: 4 Name: HeaderUnk3 Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.HeaderUnk3, buffer, ref offset);
            //Type: BaseSubCommand6D Field: 5 Name: CommandSize Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.CommandSize, buffer, ref offset);
            //Type: UnknownSubCommand6DCommand Field: 1 Name: UnknownBytes Type: Byte[];
            PrimitiveArrayTypeSerializerStrategy<byte>.Instance.Write(value.UnknownBytes, buffer, ref offset);
        }
    }
}