using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma;

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="BankItem"/>
    /// </summary>
    public sealed partial class BankItem_Serializer
            : BaseAutoGeneratedSerializerStrategy<BankItem_Serializer, BankItem>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(BankItem value, Span<byte> buffer, ref int offset)
        {
            //Type: BankItem Field: 1 Name: ItemData Type: Byte[];
            value.ItemData = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_24>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(BankItem value, Span<byte> buffer, ref int offset)
        {
            //Type: BankItem Field: 1 Name: ItemData Type: Byte[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_24>.Instance.Write(value.ItemData, buffer, ref offset);
        }
        private sealed class StaticTypedNumeric_Int32_24 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 24; }
    }
}