using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma.Proxy;

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="BindingsConfig"/>
    /// </summary>
    public sealed partial class BindingsConfig_Serializer
            : BaseAutoGeneratedSerializerStrategy<BindingsConfig_Serializer, BindingsConfig>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(BindingsConfig value, Span<byte> buffer, ref int offset)
        {
            //Type: BindingsConfig Field: 1 Name: KeyConfiguration Type: Byte[];
            value.KeyConfiguration = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_364>.Instance.Read(buffer, ref offset);
            //Type: BindingsConfig Field: 2 Name: JoystickConfiguration Type: Byte[];
            value.JoystickConfiguration = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_56>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(BindingsConfig value, Span<byte> buffer, ref int offset)
        {
            //Type: BindingsConfig Field: 1 Name: KeyConfiguration Type: Byte[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_364>.Instance.Write(value.KeyConfiguration, buffer, ref offset);
            //Type: BindingsConfig Field: 2 Name: JoystickConfiguration Type: Byte[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_56>.Instance.Write(value.JoystickConfiguration, buffer, ref offset);
        }
        private sealed class StaticTypedNumeric_Int32_364 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 364; }
        private sealed class StaticTypedNumeric_Int32_56 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 56; }
    }
}