using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using Booma;

namespace FreecraftCore.Serializer
{
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	//THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
	/// <summary>
	/// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
	/// code for the Type: <see cref = "CharacterOptionsConfiguration"/>
	/// </summary>
	public sealed partial class CharacterOptionsConfiguration_Serializer : BaseAutoGeneratedSerializerStrategy<CharacterOptionsConfiguration_Serializer, CharacterOptionsConfiguration>
	{
		/// <summary>
		/// Auto-generated deserialization/read method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalRead(CharacterOptionsConfiguration value, Span<byte> buffer, ref int offset)
		{
			//Type: CharacterOptionsConfiguration Field: 1 Name: unk Type: Byte[]
			;
			value.unk = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_276>.Instance.Read(buffer, ref offset);
			//Type: CharacterOptionsConfiguration Field: 2 Name: Bindings Type: BindingsConfig
			;
			value.Bindings = BindingsConfig_Serializer.Instance.Read(buffer, ref offset);
			//Type: CharacterOptionsConfiguration Field: 3 Name: GuildCard Type: UInt32
			;
			value.GuildCard = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
			//Type: CharacterOptionsConfiguration Field: 4 Name: TeamInfo Type: AccountTeamInformation
			;
			value.TeamInfo = AccountTeamInformation_Serializer.Instance.Read(buffer, ref offset);
		}

		/// <summary>
		/// Auto-generated serialization/write method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalWrite(CharacterOptionsConfiguration value, Span<byte> buffer, ref int offset)
		{
			//Type: CharacterOptionsConfiguration Field: 1 Name: unk Type: Byte[]
			;
			FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_276>.Instance.Write(value.unk, buffer, ref offset);
			//Type: CharacterOptionsConfiguration Field: 2 Name: Bindings Type: BindingsConfig
			;
			BindingsConfig_Serializer.Instance.Write(value.Bindings, buffer, ref offset);
			//Type: CharacterOptionsConfiguration Field: 3 Name: GuildCard Type: UInt32
			;
			GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.GuildCard, buffer, ref offset);
			//Type: CharacterOptionsConfiguration Field: 4 Name: TeamInfo Type: AccountTeamInformation
			;
			AccountTeamInformation_Serializer.Instance.Write(value.TeamInfo, buffer, ref offset);
		}

		private sealed class StaticTypedNumeric_Int32_276 : StaticTypedNumeric<Int32>
		{
			public sealed override Int32 Value => 276;
		}
	}
}